apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-6xo4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-6xo4
    app.kubernetes.io/part-of: tkrw-pr714-0075-0064-app
  name: devfile-sample-6xo4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-6xo4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-6xo4
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0064-tenant/tkrw-pr714-0075-0064-app/devfile-sample-6xo4@sha256:b6cede7cec98908f421ec3c016a04d0588983c4b28f03c2b80718c087a02b47d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
