apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-6xo4
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0064-tenant/tkrw-pr714-0075-0064-app/devfile-sample-6xo4@sha256:b6cede7cec98908f421ec3c016a04d0588983c4b28f03c2b80718c087a02b47d
        name: my-nodejs
        resources: {}
status: {}
